name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Call postman API
          run: |
            echo "Hello Charles"
            echo "This is great!"
          shell: bash
